version: '3.8'

services:
  mongoreplica01:
    image: mongo:latest
    container_name: mongo-replica-01
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "mongoReplicaSet","--wiredTigerCacheSizeGB","2", "--bind_ip", "localhost,mongo-replica-01"]
    networks:
      - mongo-replica-cluster
    volumes:
      - ./volume/mongoreplica01:/data/db

  mongoreplica02:
    image: mongo:latest
    container_name: mongo-replica-02
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "mongoReplicaSet", "--wiredTigerCacheSizeGB", "2", "--bind_ip","localhost,mongo-replica-02"]
    networks:
      - mongo-replica-cluster
    volumes:
      - ./volume/mongoreplica02:/data/db

  mongoreplica03:
    image: mongo:latest
    container_name: mongo-replica-03
    ports:
      - "27019:27017"
    command: ["mongod", "--replSet", "mongoReplicaSet","--wiredTigerCacheSizeGB","2", "--bind_ip","localhost,mongo-replica-03"]
    networks:
      - mongo-replica-cluster
    volumes:
      - ./volume/mongoreplica03:/data/db


networks:
  mongo-replica-cluster:
    driver: bridge
